version: '3.8'

services:
  web:
    image: diet-self-perception:latest
    ports:
      - "8000:8000"
    volumes:
      - ./data.db:/app/data.db
    restart: always
    environment:
      - UVICORN_RELOAD=false
      - PYTHONUNBUFFERED=1
