version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data.db:/app/data.db
      - ./app:/app
    restart: always
    environment:
      - UVICORN_RELOAD=true